import { UserType } from "../../../enums/UserType";
import { UserRole } from "../../../enums/UserRole";
import { Role } from "../../../enums/Role";
import { Department } from "../../../enums/Department";
import { Permission } from "../../../enums/Permission";
import { RoleLevel } from "../../../enums/RoleLevel";
import { AccessType } from "../../../enums/AccessType";
import { UserDto } from "./UserDto";

export const fakeUsers: UserDto[] = [
  // {
  //   id: 1,
  //   email: "admin@school.com",
  //   phone: "+905551111111",
  //   firstName: "Ali",
  //   lastName: "Yılmaz",
  //   fullName: "Ali Yılmaz",
  //   userType: UserType.INSTITUTION_USER,
  //   isEmailVerified: true,
  //   isPhoneVerified: true,
  //   lastLoginAt: "2025-08-27T09:00:00Z",
  //   profileImageUrl: "https://randomuser.me/api/portraits/men/10.jpg",
  //   isActive: true,
  //   createdAt: "2025-01-10T08:00:00Z",
  //   country: "Turkey",
  //   province: "Istanbul",
  //   district: "Besiktas",
  //   neighborhood: "Levent",
  //   addressLine1: "Levent Mah. No:1",
  //   addressLine2: "Kat:2",
  //   postalCode: "34330",
  //   latitude: 41.0851,
  //   longitude: 29.0113,
  //   userRoles: [
  //     {
  //       userId: 1,
  //       role: Role.ADMIN,
  //       departments: [Department.IT, Department.MANAGEMENT],
  //       permissions: [Permission.GENERAL, Permission.USER_CREATE],
  //       roleLevel: RoleLevel.SYSTEM,
  //       expiresAt: "2026-01-01T00:00:00Z",
  //     },
  //   ],
  //   institutionAccess: [
  //     {
  //       id: 1,
  //       userId: 1,
  //       userFullName: "Ali Yılmaz",
  //       accessType: AccessType.BRAND,
  //       entityId: 100,
  //       entityName: "Genixo Okulları",
  //       grantedAt: "2025-01-10T08:00:00Z",
  //       expiresAt: "2026-01-01T00:00:00Z",
  //       isActive: true,
  //     },
  //   ],
  // },
  // {
  //   id: 2,
  //   email: "veli@parent.com",
  //   phone: "+905552222222",
  //   firstName: "Ayşe",
  //   lastName: "Kaya",
  //   fullName: "Ayşe Kaya",
  //   userType: UserType.PARENT,
  //   isEmailVerified: false,
  //   isPhoneVerified: true,
  //   lastLoginAt: "2025-08-26T15:30:00Z",
  //   profileImageUrl: "https://randomuser.me/api/portraits/women/20.jpg",
  //   isActive: true,
  //   createdAt: "2025-02-20T10:00:00Z",
  //   country: "Turkey",
  //   province: "Ankara",
  //   district: "Cankaya",
  //   neighborhood: "Kavaklidere",
  //   addressLine1: "Kavaklidere Cad. No:5",
  //   addressLine2: "",
  //   postalCode: "06680",
  //   latitude: 39.9208,
  //   longitude: 32.8541,
  //   userRoles: [
  //     {
  //       userId: 2,
  //       role: Role.USER,
  //       departments: [Department.AUTHOR_REVIEWER],
  //       permissions: [Permission.USER_CREATE],
  //       roleLevel: RoleLevel.SCHOOL,
  //       expiresAt: "2025-12-31T00:00:00Z",
  //     },
  //   ],
  //   institutionAccess: [
  //     {
  //       id: 2,
  //       userId: 2,
  //       userFullName: "Ayşe Kaya",
  //       accessType: AccessType.SCHOOL,
  //       entityId: 200,
  //       entityName: "Ankara Koleji",
  //       grantedAt: "2025-02-20T10:00:00Z",
  //       expiresAt: "2025-12-31T00:00:00Z",
  //       isActive: true,
  //     },
  //   ],
  // },
  // {
  //   id: 3,
  //   email: "candidate@company.com",
  //   phone: "+905553333333",
  //   firstName: "Mehmet",
  //   lastName: "Demir",
  //   fullName: "Mehmet Demir",
  //   userType: UserType.INSTITUTION_USER,
  //   isEmailVerified: true,
  //   isPhoneVerified: false,
  //   lastLoginAt: "2025-08-25T12:00:00Z",
  //   profileImageUrl: "https://randomuser.me/api/portraits/men/30.jpg",
  //   isActive: false,
  //   createdAt: "2025-03-15T11:00:00Z",
  //   country: "Turkey",
  //   province: "Izmir",
  //   district: "Bornova",
  //   neighborhood: "Kazımdirik",
  //   addressLine1: "Kazımdirik Mah. No:7",
  //   addressLine2: "Daire:3",
  //   postalCode: "35000",
  //   latitude: 38.4622,
  //   longitude: 27.222,
  //   userRoles: [
  //     {
  //       userId: 3,
  //       role: Role.CANDIDATE,
  //       departments: [Department.GRADER],
  //       permissions: [Permission.GENERAL],
  //       roleLevel: RoleLevel.CAMPUS,
  //       expiresAt: "2025-09-01T00:00:00Z",
  //     },
  //   ],
  //   institutionAccess: [
  //     {
  //       id: 3,
  //       userId: 3,
  //       userFullName: "Mehmet Demir",
  //       accessType: AccessType.CAMPUS,
  //       entityId: 300,
  //       entityName: "Izmir Kampüsü",
  //       grantedAt: "2025-03-15T11:00:00Z",
  //       expiresAt: "2025-09-01T00:00:00Z",
  //       isActive: false,
  //     },
  //   ],
  // },
  // {
  //   id: 4,
  //   email: "company@business.com",
  //   phone: "+905554444444",
  //   firstName: "Zeynep",
  //   lastName: "Çelik",
  //   fullName: "Zeynep Çelik",
  //   userType: UserType.INSTITUTION_USER,
  //   isEmailVerified: true,
  //   isPhoneVerified: true,
  //   lastLoginAt: "2025-08-24T18:00:00Z",
  //   profileImageUrl: "https://randomuser.me/api/portraits/women/40.jpg",
  //   isActive: true,
  //   createdAt: "2025-04-10T09:00:00Z",
  //   country: "Turkey",
  //   province: "Bursa",
  //   district: "Nilüfer",
  //   neighborhood: "Görükle",
  //   addressLine1: "Görükle Mah. No:12",
  //   addressLine2: "Kat:1",
  //   postalCode: "16285",
  //   latitude: 40.2321,
  //   longitude: 28.8497,
  //   userRoles: [
  //     {
  //       userId: 4,
  //       role: Role.COMPANY,
  //       departments: [Department.MANAGEMENT, Department.REVIEWER],
  //       permissions: [Permission.GENERAL],
  //       roleLevel: RoleLevel.BRAND,
  //       expiresAt: "2026-04-10T00:00:00Z",
  //     },
  //   ],
  //   institutionAccess: [
  //     {
  //       id: 4,
  //       userId: 4,
  //       userFullName: "Zeynep Çelik",
  //       accessType: AccessType.BRAND,
  //       entityId: 400,
  //       entityName: "Bursa Eğitim",
  //       grantedAt: "2025-04-10T09:00:00Z",
  //       expiresAt: "2026-04-10T00:00:00Z",
  //       isActive: true,
  //     },
  //   ],
  // },
  // {
  //   id: 5,
  //   email: "author@school.com",
  //   phone: "+905555555555",
  //   firstName: "Burak",
  //   lastName: "Aydın",
  //   fullName: "Burak Aydın",
  //   userType: UserType.INSTITUTION_USER,
  //   isEmailVerified: true,
  //   isPhoneVerified: true,
  //   lastLoginAt: "2025-08-23T14:00:00Z",
  //   profileImageUrl: "https://randomuser.me/api/portraits/men/50.jpg",
  //   isActive: true,
  //   createdAt: "2025-05-05T10:00:00Z",
  //   country: "Turkey",
  //   province: "Antalya",
  //   district: "Muratpaşa",
  //   neighborhood: "Şirinyalı",
  //   addressLine1: "Şirinyalı Mah. No:8",
  //   addressLine2: "Kat:3",
  //   postalCode: "07160",
  //   latitude: 36.8791,
  //   longitude: 30.7133,
  //   userRoles: [
  //     {
  //       userId: 5,
  //       role: Role.USER,
  //       departments: [Department.AUTHOR, Department.AUTHOR_REVIEWER],
  //       permissions: [Permission.USER_CREATE],
  //       roleLevel: RoleLevel.SCHOOL,
  //       expiresAt: "2026-05-05T00:00:00Z",
  //     },
  //   ],
  //   institutionAccess: [
  //     {
  //       id: 5,
  //       userId: 5,
  //       userFullName: "Burak Aydın",
  //       accessType: AccessType.SCHOOL,
  //       entityId: 500,
  //       entityName: "Antalya Koleji",
  //       grantedAt: "2025-05-05T10:00:00Z",
  //       expiresAt: "2026-05-05T00:00:00Z",
  //       isActive: true,
  //     },
  //   ],
  // },
  // {
  //   id: 6,
  //   email: "supervisor@school.com",
  //   phone: "+905556666666",
  //   firstName: "Selin",
  //   lastName: "Kurt",
  //   fullName: "Selin Kurt",
  //   userType: UserType.INSTITUTION_USER,
  //   isEmailVerified: true,
  //   isPhoneVerified: false,
  //   lastLoginAt: "2025-08-22T11:00:00Z",
  //   profileImageUrl: "https://randomuser.me/api/portraits/women/60.jpg",
  //   isActive: false,
  //   createdAt: "2025-06-12T09:00:00Z",
  //   country: "Turkey",
  //   province: "Samsun",
  //   district: "Atakum",
  //   neighborhood: "Cumhuriyet",
  //   addressLine1: "Cumhuriyet Mah. No:15",
  //   addressLine2: "Kat:4",
  //   postalCode: "55200",
  //   latitude: 41.3167,
  //   longitude: 36.2928,
  //   userRoles: [
  //     {
  //       userId: 6,
  //       role: Role.ADMIN,
  //       departments: [Department.SUPERVISOR],
  //       permissions: [Permission.GENERAL],
  //       roleLevel: RoleLevel.SYSTEM,
  //       expiresAt: "2026-06-12T00:00:00Z",
  //     },
  //   ],
  //   institutionAccess: [
  //     {
  //       id: 6,
  //       userId: 6,
  //       userFullName: "Selin Kurt",
  //       accessType: AccessType.CAMPUS,
  //       entityId: 600,
  //       entityName: "Samsun Kampüsü",
  //       grantedAt: "2025-06-12T09:00:00Z",
  //       expiresAt: "2026-06-12T00:00:00Z",
  //       isActive: false,
  //     },
  //   ],
  // },
];
