export const feeTypeOptions = [
  { value: "ACADEMIC", label: "Akademik" },
  { value: "ADMINISTRATIVE", label: "İdari" },
  { value: "FACILITY", label: "Tesis" },
  { value: "TECHNOLOGY", label: "Teknoloji" },
  { value: "EQUIPMENT", label: "Ekipman" },
  { value: "SERVICE", label: "Hizmet" },
  { value: "ACTIVITY", label: "Aktivite" },
  { value: "TRANSPORTATION", label: "Ulaşım" },
  { value: "MEAL", label: "Yemek" },
  { value: "ACCOMMODATION", label: "Konaklama" },
  { value: "INSURANCE", label: "Sigorta" },
  { value: "SECURITY", label: "Güvenlik" },
  { value: "MAINTENANCE", label: "Bakım" },
  { value: "UTILITIES", label: "Kamu Hizmetleri" },
  { value: "MATERIALS", label: "Malzemeler" },
  { value: "EXAMINATION", label: "Sınav" },
  { value: "CERTIFICATION", label: "Sertifika" },
  { value: "GRADUATION", label: "Mezuniyet" },
  { value: "PENALTY", label: "Ceza" },
  { value: "DEPOSIT", label: "Depozito" },
  { value: "REFUNDABLE_DEPOSIT", label: "İade Edilebilir Depozito" },
  { value: "MEMBERSHIP", label: "Üyelik" },
  { value: "REGISTRATION", label: "Kayıt" },
  { value: "PROCESSING", label: "İşlem" },
  { value: "LATE_FEE", label: "Gecikme Ücreti" },
  { value: "CANCELLATION", label: "İptal" },
  { value: "REPLACEMENT", label: "Değiştirme" },
  { value: "DAMAGE", label: "Hasar" },
  { value: "LOST_ITEM", label: "Kayıp Eşya" },
  { value: "SPECIAL_EVENT", label: "Özel Etkinlik" },
  { value: "FIELD_TRIP", label: "Gezi" },
  { value: "SUMMER_PROGRAM", label: "Yaz Programı" },
  { value: "WINTER_PROGRAM", label: "Kış Programı" },
  { value: "TUTORING", label: "Özel Ders" },
  { value: "COUNSELING", label: "Danışmanlık" },
  { value: "HEALTH_SERVICE", label: "Sağlık Hizmeti" },
  { value: "LIBRARY", label: "Kütüphane" },
  { value: "LABORATORY", label: "Laboratuvar" },
  { value: "WORKSHOP", label: "Atölye" },
  { value: "CLUB", label: "Kulüp" },
  { value: "SPORTS", label: "Spor" },
  { value: "ART", label: "Sanat" },
  { value: "MUSIC", label: "Müzik" },
  { value: "OTHER", label: "Diğer" },
];
