import { SurveyDto } from "@/types";

export const MOCK_SURVEYS: SurveyDto[] = [
  {
    id: 1,
    title: "Genel Memnuniyet Anketi",
    description:
      "Eğitim hizmetlerimiz hakkındaki görüşleriniz bizim için değerlidir.",
    surveyType: "GENERAL_FEEDBACK",
    triggerEvent: "MANUAL_SEND",
    isActive: true,
    isAnonymous: false,
    isMandatory: false,
    showResultsToPublic: true,
    sendDelayHours: 24,
    reminderDelayHours: 48,
    maxReminders: 2,
    expiresAfterDays: 7,
    primaryColor: "#2563eb",
    logoUrl: "/assets/images/logo.png",
    headerImageUrl: "/assets/images/survey-header.jpg",
    welcomeMessage: "Anketimize katıldığınız için teşekkür ederiz!",
    thankYouMessage:
      "Görüşleriniz için teşekkürler. Geri bildiriminiz bizim için çok değerli.",
    completionRedirectUrl: "/surveys/thank-you",
    emailSubject: "Görüşlerinizi Paylaşın",
    emailBody:
      "Merhaba, eğitim hizmetlerimiz hakkındaki görüşlerinizi almak isteriz.",
    totalSent: 150,
    totalStarted: 120,
    totalCompleted: 95,
    averageCompletionTimeSeconds: 180,
    averageRating: 4.5,
    startRate: 80.0,
    completionRate: 79.2,
    questionCount: 5,
    estimatedDuration: "3-5 dakika",
    hasRatingQuestions: true,
    questions: [
      {
        id: 101,
        surveyId: 1,
        questionText: "Eğitim kalitemizi nasıl değerlendiriyorsunuz?",
        description: "1-5 arası puan vererek değerlendiriniz",
        questionType: "RATING_STAR",
        ratingCategory: "ACADEMIC_QUALITY",
        isRequired: true,
        sortOrder: 1,
        isActive: true,
        ratingScaleMin: 1,
        ratingScaleMax: 5,
        ratingScaleStep: 1,
        totalResponses: 95,
        averageRating: 4.5,
        skipCount: 0,
        questionTypeDisplayName: "Yıldız Değerlendirme",
        ratingCategoryDisplayName: "Akademik Kalite",
        responseRate: 100.0,
        skipRate: 0.0,
      },
      {
        id: 102,
        surveyId: 1,
        questionText: "Hangi hizmetlerimizden memnun kaldınız?",
        description: "Birden fazla seçenek işaretleyebilirsiniz",
        questionType: "MULTIPLE_CHOICE",
        isRequired: true,
        sortOrder: 2,
        isActive: true,
        options:
          '["Eğitim Programları", "Öğretmen Kalitesi", "Kampüs İmkanları", "İletişim"]',
        allowOtherOption: true,
        otherOptionLabel: "Diğer",
        optionsList: [
          "Eğitim Programları",
          "Öğretmen Kalitesi",
          "Kampüs İmkanları",
          "İletişim",
        ],
        totalResponses: 95,
        skipCount: 0,
        questionTypeDisplayName: "Çoklu Seçim",
        responseRate: 100.0,
        skipRate: 0.0,
      },
      {
        id: 103,
        surveyId: 1,
        questionText: "Tesislerimizi nasıl değerlendiriyorsunuz?",
        questionType: "RATING_SCALE",
        ratingCategory: "FACILITIES",
        isRequired: true,
        sortOrder: 3,
        isActive: true,
        ratingScaleMin: 1,
        ratingScaleMax: 10,
        ratingScaleStep: 1,
        ratingLabels: '{"1": "Çok Kötü", "5": "Orta", "10": "Mükemmel"}',
        ratingLabelsMap: {
          "1": "Çok Kötü",
          "5": "Orta",
          "10": "Mükemmel",
        },
        totalResponses: 92,
        averageRating: 8.2,
        skipCount: 3,
        questionTypeDisplayName: "Ölçek Değerlendirme",
        ratingCategoryDisplayName: "Tesisler",
        responseRate: 96.8,
        skipRate: 3.2,
      },
      {
        id: 104,
        surveyId: 1,
        questionText: "Bizi başkalarına tavsiye eder misiniz?",
        questionType: "YES_NO",
        ratingCategory: "RECOMMENDATION",
        isRequired: true,
        sortOrder: 4,
        isActive: true,
        totalResponses: 95,
        skipCount: 0,
        questionTypeDisplayName: "Evet/Hayır",
        ratingCategoryDisplayName: "Tavsiye",
        responseRate: 100.0,
        skipRate: 0.0,
      },
      {
        id: 105,
        surveyId: 1,
        questionText: "Ek görüş ve önerileriniz nelerdir?",
        description: "Lütfen görüşlerinizi detaylı bir şekilde paylaşın",
        questionType: "TEXT_LONG",
        isRequired: false,
        sortOrder: 5,
        isActive: true,
        textMinLength: 10,
        textMaxLength: 500,
        placeholderText: "Görüşlerinizi buraya yazabilirsiniz...",
        totalResponses: 68,
        skipCount: 27,
        questionTypeDisplayName: "Uzun Metin",
        responseRate: 71.6,
        skipRate: 28.4,
      },
    ],
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T15:30:00Z",
  },
  {
    id: 2,
    title: "Randevu Geri Bildirimi",
    description: "Randevu deneyiminiz hakkında görüşlerinizi öğrenmek isteriz.",
    surveyType: "APPOINTMENT_FEEDBACK",
    triggerEvent: "APPOINTMENT_COMPLETED",
    isActive: true,
    isAnonymous: true,
    isMandatory: false,
    showResultsToPublic: false,
    sendDelayHours: 2,
    reminderDelayHours: 24,
    maxReminders: 1,
    expiresAfterDays: 3,
    primaryColor: "#10b981",
    welcomeMessage: "Randevu deneyiminizi değerlendirin",
    thankYouMessage: "Geri bildiriminiz için teşekkür ederiz!",
    emailSubject: "Randevunuz Hakkında",
    emailBody: "Merhaba, randevu deneyiminizi değerlendirmenizi rica ederiz.",
    totalSent: 85,
    totalStarted: 72,
    totalCompleted: 64,
    averageCompletionTimeSeconds: 120,
    averageRating: 4.7,
    startRate: 84.7,
    completionRate: 88.9,
    questionCount: 3,
    estimatedDuration: "2 dakika",
    hasRatingQuestions: true,
    questions: [
      {
        id: 201,
        surveyId: 2,
        questionText: "Randevu sürecinizi nasıl değerlendiriyorsunuz?",
        questionType: "RATING_STAR",
        ratingCategory: "OVERALL_SATISFACTION",
        isRequired: true,
        sortOrder: 1,
        isActive: true,
        ratingScaleMin: 1,
        ratingScaleMax: 5,
        ratingScaleStep: 1,
        totalResponses: 64,
        averageRating: 4.7,
        skipCount: 0,
        questionTypeDisplayName: "Yıldız Değerlendirme",
        ratingCategoryDisplayName: "Genel Memnuniyet",
        responseRate: 100.0,
        skipRate: 0.0,
      },
      {
        id: 202,
        surveyId: 2,
        questionText: "Personel tutumu nasıldı?",
        questionType: "LIKERT_SCALE",
        ratingCategory: "STAFF_FRIENDLINESS",
        isRequired: true,
        sortOrder: 2,
        isActive: true,
        options: '["Çok Kötü", "Kötü", "Orta", "İyi", "Çok İyi"]',
        optionsList: ["Çok Kötü", "Kötü", "Orta", "İyi", "Çok İyi"],
        totalResponses: 64,
        skipCount: 0,
        questionTypeDisplayName: "Likert Ölçeği",
        ratingCategoryDisplayName: "Personel Nezaketi",
        responseRate: 100.0,
        skipRate: 0.0,
      },
      {
        id: 203,
        surveyId: 2,
        questionText: "Ek yorumlarınız",
        questionType: "TEXT_SHORT",
        isRequired: false,
        sortOrder: 3,
        isActive: true,
        textMaxLength: 200,
        placeholderText: "İsteğe bağlı...",
        totalResponses: 42,
        skipCount: 22,
        questionTypeDisplayName: "Kısa Metin",
        responseRate: 65.6,
        skipRate: 34.4,
      },
    ],
    createdAt: "2024-02-01T08:00:00Z",
    updatedAt: "2024-02-10T12:00:00Z",
  },
];
