import { SurveyResponseDto } from "@/types";

export const MOCK_SURVEYS: SurveyResponseDto[] = [
  {
    id: 1,
    surveyId: 1,
    surveyTitle: "Randevu Geri Bildirim Anketi",
    respondentUserId: 1,
    respondentUserName: "Test Kullanıcı",
    schoolId: 1,
    schoolName: "Eğitim Dünyası Test Anaokulu",
    appointmentId: 1,
    responseToken: "test-token-1",
    status: "INVITED",
    startedAt: "2025-10-30T09:00:00Z",
    statusDisplayName: "Davet Edildi",
    progressPercentage: 0,
    isComplete: false,
    isExpired: false,
    reminderCount: 0,
    createdAt: "2025-10-30T09:00:00Z",
    updatedAt: "2025-10-30T09:00:00Z",
  },
  {
    id: 2,
    surveyId: 2,
    surveyTitle: "Genel Memnuniyet Anketi",
    respondentUserId: 1,
    respondentUserName: "Test Kullanıcı",
    schoolId: 1,
    schoolName: "Eğitim Dünyası Test Anaokulu",
    appointmentId: 2,
    responseToken: "test-token-2",
    status: "STARTED",
    startedAt: "2025-10-29T14:00:00Z",
    statusDisplayName: "Başlatıldı",
    progressPercentage: 25,
    isComplete: false,
    isExpired: false,
    reminderCount: 1,
    createdAt: "2025-10-29T14:00:00Z",
    updatedAt: "2025-10-29T14:30:00Z",
  },
  {
    id: 3,
    surveyId: 3,
    surveyTitle: "Eğitim Kalitesi Değerlendirmesi",
    respondentUserId: 1,
    respondentUserName: "Test Kullanıcı",
    schoolId: 1,
    schoolName: "Eğitim Dünyası Test Anaokulu",
    appointmentId: 3,
    responseToken: "test-token-3",
    status: "COMPLETED",
    startedAt: "2025-10-28T10:00:00Z",
    completedAt: "2025-10-28T10:15:00Z",
    statusDisplayName: "Tamamlandı",
    progressPercentage: 100,
    isComplete: true,
    isExpired: false,
    reminderCount: 0,
    overallRating: 4.5,
    createdAt: "2025-10-28T10:00:00Z",
    updatedAt: "2025-10-28T10:15:00Z",
  },
];
