import { SurveyDto } from "@/types";

export const MOCK_SURVEYS: SurveyDto[] = [
  {
    id: 1,
    title: "Genel Memnuniyet Anketi",
    description:
      "Eğitim hizmetlerimiz hakkındaki görüşleriniz bizim için değerlidir.",
    surveyType: "GENERAL_FEEDBACK",
    triggerEvent: "MANUAL_SEND",
    isActive: true,
    isAnonymous: false,
    isMandatory: false,
    showResultsToPublic: true,
    sendDelayHours: 24,
    reminderDelayHours: 48,
    maxReminders: 2,
    expiresAfterDays: 7,
    primaryColor: "#2563eb",
    logoUrl: "/assets/images/logo.png",
    headerImageUrl: "/assets/images/survey-header.jpg",
    welcomeMessage: "Anketimize katıldığınız için teşekkür ederiz!",
    thankYouMessage:
      "Görüşleriniz için teşekkürler. Geri bildiriminiz bizim için çok değerli.",
    completionRedirectUrl: "/surveys/thank-you",
    emailSubject: "Görüşlerinizi Paylaşın",
    emailBody:
      "Merhaba, eğitim hizmetlerimiz hakkındaki görüşlerinizi almak isteriz.",
    totalSent: 150,
    totalStarted: 120,
    totalCompleted: 95,
    averageCompletionTimeSeconds: 180,
    averageRating: 4.5,
    startRate: 80.0,
    completionRate: 79.2,
    questionCount: 5,
    estimatedDuration: "3-5 dakika",
    hasRatingQuestions: true,
    questions: [
      {
        id: 101,
        surveyId: 1,
        questionText: "Eğitim kalitemizi nasıl değerlendiriyorsunuz?",
        description: "1-5 arası puan vererek değerlendiriniz",
        questionType: "RATING_STAR",
        ratingCategory: "ACADEMIC_QUALITY",
        isRequired: true,
        sortOrder: 1,
        isActive: true,
        ratingScaleMin: 1,
        ratingScaleMax: 5,
        ratingScaleStep: 1,
        totalResponses: 95,
        averageRating: 4.5,
        skipCount: 0,
        questionTypeDisplayName: "Yıldız Değerlendirme",
        ratingCategoryDisplayName: "Akademik Kalite",
        responseRate: 100.0,
        skipRate: 0.0,
      },
      {
        id: 102,
        surveyId: 1,
        questionText: "Öğretmen kalitemizi nasıl değerlendiriyorsunuz?",
        description: "1-5 arası puan vererek değerlendiriniz",
        questionType: "RATING_STAR",
        ratingCategory: "STAFF_FRIENDLINESS",
        isRequired: true,
        sortOrder: 2,
        isActive: true,
        ratingScaleMin: 1,
        ratingScaleMax: 5,
        ratingScaleStep: 1,
        totalResponses: 95,
        averageRating: 4.3,
        skipCount: 0,
        questionTypeDisplayName: "Yıldız Değerlendirme",
        ratingCategoryDisplayName: "Öğretmen Kalitesi",
        responseRate: 100.0,
        skipRate: 0.0,
      },
      {
        id: 103,
        surveyId: 1,
        questionText: "Tesislerimizi nasıl değerlendiriyorsunuz?",
        description: "Kampüs ve eğitim tesisleri için 1-5 arası puan veriniz",
        questionType: "RATING_STAR",
        ratingCategory: "FACILITIES",
        isRequired: true,
        sortOrder: 3,
        isActive: true,
        ratingScaleMin: 1,
        ratingScaleMax: 5,
        ratingScaleStep: 1,
        totalResponses: 92,
        averageRating: 4.1,
        skipCount: 3,
        questionTypeDisplayName: "Yıldız Değerlendirme",
        ratingCategoryDisplayName: "Tesisler",
        responseRate: 96.8,
        skipRate: 3.2,
      },
      {
        id: 104,
        surveyId: 1,
        questionText: "Bizi başkalarına tavsiye etme olasılığınız nedir?",
        description:
          "1-5 arası puan vererek tavsiye etme isteğinizi belirtiniz",
        questionType: "RATING_STAR",
        ratingCategory: "RECOMMENDATION",
        isRequired: true,
        sortOrder: 4,
        isActive: true,
        ratingScaleMin: 1,
        ratingScaleMax: 5,
        ratingScaleStep: 1,
        totalResponses: 95,
        averageRating: 4.6,
        skipCount: 0,
        questionTypeDisplayName: "Yıldız Değerlendirme",
        ratingCategoryDisplayName: "Tavsiye",
        responseRate: 100.0,
        skipRate: 0.0,
      },
      {
        id: 105,
        surveyId: 1,
        questionText: "Genel memnuniyet derecenizi nasıl değerlendiriyorsunuz?",
        description: "Tüm hizmetlerimizi genel olarak 1-5 arası puanlayınız",
        questionType: "RATING_STAR",
        ratingCategory: "OVERALL_SATISFACTION",
        isRequired: false,
        sortOrder: 5,
        isActive: true,
        ratingScaleMin: 1,
        ratingScaleMax: 5,
        ratingScaleStep: 1,
        totalResponses: 68,
        averageRating: 4.2,
        skipCount: 27,
        questionTypeDisplayName: "Yıldız Değerlendirme",
        ratingCategoryDisplayName: "Genel Memnuniyet",
        responseRate: 71.6,
        skipRate: 28.4,
      },
    ],
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T15:30:00Z",
  },
  {
    id: 2,
    title: "Randevu Geri Bildirimi",
    description: "Randevu deneyiminiz hakkında görüşlerinizi öğrenmek isteriz.",
    surveyType: "APPOINTMENT_FEEDBACK",
    triggerEvent: "APPOINTMENT_COMPLETED",
    isActive: true,
    isAnonymous: true,
    isMandatory: false,
    showResultsToPublic: false,
    sendDelayHours: 2,
    reminderDelayHours: 24,
    maxReminders: 1,
    expiresAfterDays: 3,
    primaryColor: "#10b981",
    welcomeMessage: "Randevu deneyiminizi değerlendirin",
    thankYouMessage: "Geri bildiriminiz için teşekkür ederiz!",
    emailSubject: "Randevunuz Hakkında",
    emailBody: "Merhaba, randevu deneyiminizi değerlendirmenizi rica ederiz.",
    totalSent: 85,
    totalStarted: 72,
    totalCompleted: 64,
    averageCompletionTimeSeconds: 120,
    averageRating: 4.7,
    startRate: 84.7,
    completionRate: 88.9,
    questionCount: 3,
    estimatedDuration: "2 dakika",
    hasRatingQuestions: true,
    questions: [
      {
        id: 201,
        surveyId: 2,
        questionText: "Randevu sürecinizi nasıl değerlendiriyorsunuz?",
        questionType: "RATING_STAR",
        ratingCategory: "OVERALL_SATISFACTION",
        isRequired: true,
        sortOrder: 1,
        isActive: true,
        ratingScaleMin: 1,
        ratingScaleMax: 5,
        ratingScaleStep: 1,
        totalResponses: 64,
        averageRating: 4.7,
        skipCount: 0,
        questionTypeDisplayName: "Yıldız Değerlendirme",
        ratingCategoryDisplayName: "Genel Memnuniyet",
        responseRate: 100.0,
        skipRate: 0.0,
      },
      {
        id: 202,
        surveyId: 2,
        questionText: "Personel tutumu nasıldı?",
        description: "Personelimizin yaklaşımını 1-5 arası puanlayınız",
        questionType: "RATING_STAR",
        ratingCategory: "STAFF_FRIENDLINESS",
        isRequired: true,
        sortOrder: 2,
        isActive: true,
        ratingScaleMin: 1,
        ratingScaleMax: 5,
        ratingScaleStep: 1,
        totalResponses: 64,
        averageRating: 4.5,
        skipCount: 0,
        questionTypeDisplayName: "Yıldız Değerlendirme",
        ratingCategoryDisplayName: "Personel Nezaketi",
        responseRate: 100.0,
        skipRate: 0.0,
      },
      {
        id: 203,
        surveyId: 2,
        questionText:
          "Randevu deneyiminizi genel olarak nasıl değerlendiriyorsunuz?",
        description: "Tüm randevu sürecini 1-5 arası puanlayınız",
        questionType: "RATING_STAR",
        ratingCategory: "OVERALL_SATISFACTION",
        isRequired: false,
        sortOrder: 3,
        isActive: true,
        ratingScaleMin: 1,
        ratingScaleMax: 5,
        ratingScaleStep: 1,
        totalResponses: 42,
        averageRating: 4.4,
        skipCount: 22,
        questionTypeDisplayName: "Yıldız Değerlendirme",
        ratingCategoryDisplayName: "Genel Memnuniyet",
        responseRate: 65.6,
        skipRate: 34.4,
      },
    ],
    createdAt: "2024-02-01T08:00:00Z",
    updatedAt: "2024-02-10T12:00:00Z",
  },
];
