export enum Department {
  AUTHOR = "AUTHOR",
  GRADER = "GRADER",
  SUPERVISOR = "SUPERVISOR",
  MANAGEMENT = "MANAGEMENT",
  IT = "IT",
  AUTHOR_REVIEWER = "AUTHOR_REVIEWER",
  ADMIN = "ADMIN",
  REVIEWER = "REVIEWER"
}
