export enum DiscountType {
  FIXED_AMOUNT = "FIXED_AMOUNT",
  PERCENTAGE = "PERCENTAGE",
  FREE_MONTHS = "FREE_MONTHS",
  BUY_X_GET_Y = "BUY_X_GET_Y",
  TIERED = "TIERED",
  BUNDLE = "BUNDLE",
  NO_DISCOUNT = "NO_DISCOUNT",
}
