export enum MessageType {
  GENERAL_INQUIRY = "GENERAL_INQUIRY", // Genel bilgi
  ENROLLMENT_INQUIRY = "ENROLLMENT_INQUIRY", // Kayıt bilgisi
  APPOINTMENT_REQUEST = "APPOINTMENT_REQUEST", // Randevu talebi
  COMPLAINT = "COMPLAINT", // Şikayet
  SUGGESTION = "SUGGESTION", // Öneri
  TECHNICAL_SUPPORT = "TECHNICAL_SUPPORT", // Teknik destek
  FINANCIAL_INQUIRY = "FINANCIAL_INQUIRY", // Mali bilgi
  TRANSPORTATION = "TRANSPORTATION", // Ulaşım
  CAFETERIA = "CAFETERIA", // Kantin
  EXTRACURRICULAR = "EXTRACURRICULAR", // Sosyal aktiviteler
  ACADEMIC_INQUIRY = "ACADEMIC_INQUIRY", // Akademik bilgi
  FACILITIES_INQUIRY = "FACILITIES_INQUIRY", // Tesis bilgisi
  CALLBACK_REQUEST = "CALLBACK_REQUEST", // Geri arama talebi
  BROCHURE_REQUEST = "BROCHURE_REQUEST", // Broşür talebi
  PARTNERSHIP = "PARTNERSHIP", // İş birliği
  MEDIA_INQUIRY = "MEDIA_INQUIRY", // Basın
  OTHER = "OTHER", // Diğer
}
