export enum Permission {
  APPROVAL = "APPROVAL",
  USER_CREATE = "USER_CREATE",
  GENERAL = "GENERAL",
  FINANCE_OPERATION = "FINANCE_OPERATION",
  ACCOUNTING_OPERATION = "ACCOUNTING_OPERATION",
  DELIVERY_OPERATION = "DELIVERY_OPERATION",
  CUSTOMER_OPERATION = "CUSTOMER_OPERATION",
  OFFER_OPERATION = "OFFER_OPERATION",
  ORDER_OPERATION = "ORDER_OPERATION",
  SUPPLIER_OPERATION = "SUPPLIER_OPERATION",
  TRANSPORTATION_OPERATION = "TRANSPORTATION_OPERATION",
  DELIVERY_DOCUMENT = "DELIVERY_DOCUMENT",
  SETTING = "SETTING"
}
