import { ResponseStatus } from "../../../enums/ResponseStatus";
import { SurveyQuestionResponseDto } from "./SurveyQuestionResponseDto";

export interface SurveyResponseDto {
  id: number;
  surveyId: number;
  surveyTitle: string;
  respondentUserId: number;
  respondentUserName: string;
  schoolId: number;
  schoolName: string;
  appointmentId: number;
  responseToken: string;
  status: ResponseStatus;
  startedAt: string;
  completedAt: string;
  submittedAt: string;
  completionTimeSeconds: number;
  respondentName: string;
  respondentEmail: string;
  respondentPhone: string;
  ipAddress: string;
  userAgent: string;
  browserInfo: string;
  deviceInfo: string;
  invitationSentAt: string;
  invitationOpenedAt: string;
  reminderCount: number;
  lastReminderSentAt: string;
  overallRating: number;
  cleanlinessRating: number;
  staffRating: number;
  facilitiesRating: number;
  communicationRating: number;
  generalFeedback: string;
  suggestions: string;
  complaints: string;
  wouldRecommend: boolean;
  likelihoodToEnroll: number;
  formattedCompletionTime: string;
  statusDisplayName: string;
  progressPercentage: number;
  isComplete: boolean;
  isExpired: boolean;
  questionResponses: SurveyQuestionResponseDto[];
  createdAt: string;
  updatedAt: string;
}
