export * from "./about-hero-section";
export * from "./section-header";
export * from "./features-section";
export * from "./how-it-works-section";
export * from "./advantages-section";
export * from "./institution-modules-section";
export * from "./mission-vision-section";
export * from "./brand-section";
export * from "./info-section";
