// Gallery type options for select
export const galleryTypeOptions = [
  { value: "MIXED", label: "Karışık" },
  { value: "PHOTOS", label: "Fotoğraflar" },
  { value: "VIDEOS", label: "Videolar" },
  { value: "SCHOOL_TOUR", label: "Okul Turu" },
  { value: "EVENTS", label: "Etkinlikler" },
  { value: "FACILITIES", label: "Tesisler" },
  { value: "CLASSROOMS", label: "Sınıflar" },
  { value: "OUTDOOR_AREAS", label: "Açık Alanlar" },
  { value: "CAFETERIA", label: "Kafeterya" },
  { value: "LIBRARY", label: "Kütüphane" },
  { value: "LABORATORY", label: "Laboratuvar" },
  { value: "SPORTS_FACILITIES", label: "Spor Tesisleri" },
  { value: "TRANSPORTATION", label: "Ulaşım" },
  { value: "ACHIEVEMENTS", label: "Başarılar" },
  { value: "GRADUATION", label: "Mezuniyet" },
  { value: "CEREMONIES", label: "Törenler" },
  { value: "DAILY_ACTIVITIES", label: "Günlük Aktiviteler" },
  { value: "STUDENT_WORK", label: "Öğrenci Çalışmaları" },
  { value: "STAFF", label: "Personel" },
  { value: "CAMPUS_LIFE", label: "Kampüs Yaşamı" },
  { value: "BEFORE_AFTER", label: "Öncesi-Sonrası" },
];
