import { CampaignDto } from "@/types/dto/campaign/CampaignDto";

export const campaignMockData: CampaignDto[] = [
  {
    id: 1,
    title: "Yaz Okulu İndirim Kampanyası",
    slug: "yaz-okulu-indirim-kampanyasi",
    description:
      "Bu yaz eğitimde yeni fırsatları yakala! %25 indirimle yaz okulu programlarımıza katıl. Profesyonel eğitmenler eşliğinde yoğun eğitim programları.",
    shortDescription: "Yaz okulu programlarında %25 indirim fırsatı",
    campaignType: "SUMMER_SCHOOL",
    discountType: "PERCENTAGE",
    discountAmount: 0,
    discountPercentage: 25,
    maxDiscountAmount: 5000,
    minPurchaseAmount: 3000,
    status: "EXPIRED",
    isFeatured: true,
    isPublic: true,
    targetAudience: "ALL",
    targetAgeMin: 6,
    targetAgeMax: 18,
    promoCode: "YAZ2025",
    badgeText: "Yaz Fırsatı",
    badgeColor: "#FF6B35",
    thumbnailImageUrl:
      "https://images.unsplash.com/photo-1544717297-fa95b6ee9643?w=400&h=300&fit=crop&crop=center",
    bannerImageUrl:
      "https://images.unsplash.com/photo-1544717297-fa95b6ee9643?w=1200&h=400&fit=crop&crop=center",
    startDate: "2025-06-01",
    endDate: "2025-08-31",
    academicYear: "2025-2026",
    termsAndConditions: "Kampanya sadece yeni kayıtlar için geçerlidir.",
    metaTitle: "Yaz Okulu İndirim Kampanyası",
    metaDescription:
      "Bu yaz eğitimde yeni fırsatları yakala! %25 indirimle yaz okulu programlarına katıl.",
    metaKeywords: "yaz okulu, indirim, eğitim, kampanya",
    viewCount: 15420,
    clickCount: 3280,
    applicationCount: 156,
    conversionCount: 89,
    conversionRate: 57.1,
    usageLimit: 200,
    usageCount: 89,
    priority: 1,
    isActive: false,
    isExpired: true,
    daysRemaining: 0,
    createdAt: "2025-05-15T10:00:00Z",
    updatedAt: "2025-08-31T23:59:59Z",
  },
  {
    id: 2,
    title: "Erken Kayıt Avantajı",
    slug: "erken-kayit-avantaji",
    description:
      "Erken kayıt yaptır, hem indirim kazan hem de öncelik al! İlk 100 kayıta özel %30 indirim. Sınırlı kontenjan ile erken kaydın avantajlarını yaşa.",
    shortDescription: "İlk 100 kayıta özel %30 erken kayıt indirimi",
    campaignType: "EARLY_BIRD",
    discountType: "PERCENTAGE",
    discountAmount: 0,
    discountPercentage: 30,
    maxDiscountAmount: 8000,
    minPurchaseAmount: 5000,
    status: "ACTIVE",
    isFeatured: true,
    isPublic: true,
    targetAudience: "NEW_STUDENTS",
    targetAgeMin: 3,
    targetAgeMax: 18,
    earlyBirdEndDate: "2025-04-30",
    registrationDeadline: "2025-05-15",
    promoCode: "ERKEN2025",
    badgeText: "Erken Kayıt",
    badgeColor: "#4CAF50",
    thumbnailImageUrl:
      "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=300&fit=crop&crop=center",
    bannerImageUrl:
      "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=1200&h=400&fit=crop&crop=center",
    startDate: "2025-03-01",
    endDate: "2025-05-31",
    academicYear: "2025-2026",
    termsAndConditions:
      "Erken kayıt kampanyası sadece yeni öğrenciler için geçerlidir. İlk 100 kayıt ile sınırlıdır.",
    metaTitle: "Erken Kayıt Avantajı Kampanyası",
    metaDescription:
      "Erken kayıt yaptır, %30 indirim kazan! İlk 100 kayıta özel fırsat.",
    metaKeywords: "erken kayıt, indirim, yeni öğrenci, kampanya",
    viewCount: 8750,
    clickCount: 2100,
    applicationCount: 89,
    conversionCount: 67,
    conversionRate: 75.3,
    usageLimit: 100,
    usageCount: 67,
    priority: 2,
    isActive: true,
    isExpired: false,
    daysRemaining: 45,
    createdAt: "2025-02-15T09:00:00Z",
    updatedAt: "2025-03-01T12:00:00Z",
  },
  {
    id: 3,
    title: "Kardeş İndirimi",
    slug: "kardes-indirimi",
    description:
      "Kardeşler birlikte öğrensin! İkinci kardeş için %50 indirim fırsatı. Aile bağlarını güçlendiren eğitim deneyimi.",
    shortDescription: "İkinci kardeş için %50 indirim",
    campaignType: "SIBLING_DISCOUNT",
    discountType: "PERCENTAGE",
    discountAmount: 0,
    discountPercentage: 50,
    maxDiscountAmount: 10000,
    minPurchaseAmount: 2000,
    status: "ACTIVE",
    isFeatured: true,
    isPublic: true,
    targetAudience: "SIBLINGS",
    targetAgeMin: 2,
    targetAgeMax: 18,
    targetSiblingDiscount: true,
    promoCode: "KARDES2025",
    badgeText: "Kardeş İndirimi",
    badgeColor: "#9C27B0",
    thumbnailImageUrl:
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=400&h=300&fit=crop&crop=center",
    bannerImageUrl:
      "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=1200&h=400&fit=crop&crop=center",
    startDate: "2025-01-01",
    endDate: "2025-12-31",
    academicYear: "2025-2026",
    termsAndConditions:
      "Kardeş indirimi sadece aynı akademik yılda kayıt yaptıran ailelere uygulanır.",
    metaTitle: "Kardeş İndirimi Kampanyası",
    metaDescription:
      "Kardeşler birlikte öğrensin! İkinci kardeş için %50 indirim.",
    metaKeywords: "kardeş indirimi, aile, indirim, kampanya",
    viewCount: 12300,
    clickCount: 2850,
    applicationCount: 234,
    conversionCount: 178,
    conversionRate: 76.1,
    usageLimit: 500,
    usageCount: 178,
    priority: 3,
    isActive: true,
    isExpired: false,
    daysRemaining: 150,
    createdAt: "2024-12-01T08:00:00Z",
    updatedAt: "2025-01-15T14:30:00Z",
  },
  {
    id: 4,
    title: "Yeni Öğrenci Paketi",
    slug: "yeni-ogrenci-paketi",
    description:
      "İlk defa katılan öğrenciler için özel paket! 1000 TL sabit indirim + ücretsiz materyal. Eğitim hayatına güçlü bir başlangıç.",
    shortDescription:
      "Yeni öğrencilere 1000 TL sabit indirim + ücretsiz materyal",
    campaignType: "NEW_STUDENT",
    discountType: "FIXED_AMOUNT",
    discountAmount: 1000,
    discountPercentage: 0,
    maxDiscountAmount: 1000,
    minPurchaseAmount: 3000,
    status: "ACTIVE",
    isFeatured: false,
    isPublic: true,
    targetAudience: "NEW_STUDENTS",
    targetNewStudentsOnly: true,
    targetAgeMin: 3,
    targetAgeMax: 18,
    promoCode: "YENI2025",
    freeServices: "Ücretsiz eğitim materyali paketi",
    bonusFeatures: "Özel mentorluk desteği",
    giftItems: "Okul çantası ve kırtasiye seti",
    badgeText: "Yeni Öğrenci",
    badgeColor: "#2196F3",
    thumbnailImageUrl:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop&crop=center",
    bannerImageUrl:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=1200&h=400&fit=crop&crop=center",
    startDate: "2025-01-15",
    endDate: "2025-06-15",
    academicYear: "2025-2026",
    termsAndConditions:
      "Kampanya sadece kurumumuza ilk kez kaydolan öğrenciler için geçerlidir.",
    metaTitle: "Yeni Öğrenci Paketi Kampanyası",
    metaDescription:
      "İlk kez katılan öğrenciler için 1000 TL indirim + ücretsiz materyal.",
    metaKeywords: "yeni öğrenci, sabit indirim, materyal, kampanya",
    viewCount: 6800,
    clickCount: 1450,
    applicationCount: 98,
    conversionCount: 76,
    conversionRate: 77.6,
    usageLimit: 150,
    usageCount: 76,
    priority: 4,
    isActive: true,
    isExpired: false,
    daysRemaining: 95,
    createdAt: "2025-01-01T10:00:00Z",
    updatedAt: "2025-02-20T16:45:00Z",
  },
  {
    id: 5,
    title: "Ücretsiz Deneme Haftası",
    slug: "ucretsiz-deneme-haftasi",
    description:
      "7 gün ücretsiz deneme! Eğitim kalitemizi riske girmeden test et. Hiçbir ödeme yapmadan programlarımızı deneyimle.",
    shortDescription: "7 gün tamamen ücretsiz deneme fırsatı",
    campaignType: "FREE_TRIAL",
    discountType: "NO_DISCOUNT",
    discountAmount: 0,
    discountPercentage: 0,
    freeTrialDays: 7,
    status: "ACTIVE",
    isFeatured: true,
    isPublic: true,
    targetAudience: "ALL",
    targetAgeMin: 3,
    targetAgeMax: 18,
    promoCode: "DENEME7",
    freeServices: "7 gün tam erişim",
    badgeText: "Ücretsiz Deneme",
    badgeColor: "#FF9800",
    thumbnailImageUrl:
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=300&fit=crop&crop=center",
    bannerImageUrl:
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=1200&h=400&fit=crop&crop=center",
    startDate: "2025-02-01",
    endDate: "2025-11-30",
    academicYear: "2025-2026",
    termsAndConditions:
      "Ücretsiz deneme sadece bir kez kullanılabilir. Kredi kartı bilgisi gerekmez.",
    metaTitle: "Ücretsiz Deneme Haftası",
    metaDescription:
      "7 gün ücretsiz deneme! Eğitim kalitemizi riske girmeden test et.",
    metaKeywords: "ücretsiz deneme, test, eğitim, kampanya",
    viewCount: 18500,
    clickCount: 4200,
    applicationCount: 567,
    conversionCount: 234,
    conversionRate: 41.3,
    usageLimit: 1000,
    usageCount: 234,
    priority: 1,
    isActive: true,
    isExpired: false,
    daysRemaining: 120,
    createdAt: "2025-01-15T11:00:00Z",
    updatedAt: "2025-03-01T09:30:00Z",
  },
  {
    id: 6,
    title: "Bahar Dönemi Özel İndirimi",
    slug: "bahar-donemi-ozel-indirimi",
    description:
      "Bahar döneminde eğitime devam edin! Mart ayına özel %20 indirim fırsatı. Yeniden doğan doğayla birlikte bilgiyi de yenile.",
    shortDescription: "Bahar dönemine özel %20 indirim",
    campaignType: "SEASONAL",
    discountType: "PERCENTAGE",
    discountAmount: 0,
    discountPercentage: 20,
    maxDiscountAmount: 4000,
    minPurchaseAmount: 2500,
    status: "PAUSED",
    isFeatured: false,
    isPublic: true,
    targetAudience: "ALL",
    targetAgeMin: 5,
    targetAgeMax: 18,
    promoCode: "BAHAR20",
    badgeText: "Bahar İndirimi",
    badgeColor: "#8BC34A",
    thumbnailImageUrl:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop&crop=center",
    bannerImageUrl:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=400&fit=crop&crop=center",
    startDate: "2025-03-01",
    endDate: "2025-05-31",
    academicYear: "2025-2026",
    termsAndConditions:
      "Bahar dönemi kampanyası geçerli dönem için kullanılabilir.",
    metaTitle: "Bahar Dönemi Özel İndirimi",
    metaDescription:
      "Bahar döneminde eğitime devam edin! %20 özel indirim fırsatı.",
    metaKeywords: "bahar, dönem, indirim, mevsimlik, kampanya",
    viewCount: 4200,
    clickCount: 890,
    applicationCount: 45,
    conversionCount: 32,
    conversionRate: 71.1,
    usageLimit: 200,
    usageCount: 32,
    priority: 5,
    isActive: false,
    isExpired: false,
    daysRemaining: 75,
    createdAt: "2025-02-15T13:00:00Z",
    updatedAt: "2025-03-10T11:20:00Z",
  },
  {
    id: 7,
    title: "Kış Kampı Programı",
    slug: "kis-kampi-programi",
    description:
      "Kış tatilini verimli geçir! Özel kış kampı programlarımızda %15 indirim. Kar eğlencesi ile birlikte öğrenme deneyimi.",
    shortDescription: "Kış kampı programlarında %15 indirim",
    campaignType: "WINTER_CAMP",
    discountType: "PERCENTAGE",
    discountAmount: 0,
    discountPercentage: 15,
    maxDiscountAmount: 3000,
    minPurchaseAmount: 4000,
    status: "COMPLETED",
    isFeatured: false,
    isPublic: true,
    targetAudience: "SPECIFIC_AGES",
    targetAgeMin: 7,
    targetAgeMax: 16,
    promoCode: "KIS15",
    badgeText: "Kış Kampı",
    badgeColor: "#607D8B",
    thumbnailImageUrl:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=300&fit=crop&crop=center",
    bannerImageUrl:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&h=400&fit=crop&crop=center",
    startDate: "2024-12-15",
    endDate: "2025-02-28",
    academicYear: "2024-2025",
    termsAndConditions: "Kış kampı programları için konaklama dahildir.",
    metaTitle: "Kış Kampı Programı",
    metaDescription:
      "Kış tatilini verimli geçir! Özel kış kampı programlarında %15 indirim.",
    metaKeywords: "kış kampı, tatil, program, indirim, kampanya",
    viewCount: 2800,
    clickCount: 650,
    applicationCount: 78,
    conversionCount: 65,
    conversionRate: 83.3,
    usageLimit: 100,
    usageCount: 65,
    priority: 6,
    isActive: false,
    isExpired: true,
    daysRemaining: 0,
    createdAt: "2024-11-01T09:00:00Z",
    updatedAt: "2025-02-28T23:59:59Z",
  },
  {
    id: 8,
    title: "Sadakat Programı",
    slug: "sadakat-programi",
    description:
      "Uzun süreli öğrencilerimize özel! 2 yıl ve üzeri için %25 sadakat indirimi. Bizimle olan yolculuğunuz ödüllendirilir.",
    shortDescription: "2+ yıl öğrencilerine %25 sadakat indirimi",
    campaignType: "LOYALTY_REWARD",
    discountType: "PERCENTAGE",
    discountAmount: 0,
    discountPercentage: 25,
    maxDiscountAmount: 6000,
    minPurchaseAmount: 2000,
    status: "ACTIVE",
    isFeatured: true,
    isPublic: true,
    targetAudience: "LOYALTY_MEMBERS",
    targetAgeMin: 3,
    targetAgeMax: 18,
    promoCode: "SADAKAT25",
    bonusFeatures: "Özel etkinlik davetleri",
    giftItems: "Sadakat rozeti ve sertifika",
    badgeText: "Sadakat Ödülü",
    badgeColor: "#795548",
    thumbnailImageUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop&crop=center",
    bannerImageUrl:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1200&h=400&fit=crop&crop=center",
    startDate: "2025-01-01",
    endDate: "2025-12-31",
    academicYear: "2025-2026",
    termsAndConditions:
      "Sadakat programı en az 2 yıl kesintisiz eğitim almış öğrencilere uygulanır.",
    metaTitle: "Sadakat Programı",
    metaDescription: "Uzun süreli öğrencilerimize özel %25 sadakat indirimi.",
    metaKeywords: "sadakat, program, indirim, ödül, kampanya",
    viewCount: 9400,
    clickCount: 1850,
    applicationCount: 123,
    conversionCount: 98,
    conversionRate: 79.7,
    usageLimit: 300,
    usageCount: 98,
    priority: 2,
    isActive: true,
    isExpired: false,
    daysRemaining: 180,
    createdAt: "2024-12-01T12:00:00Z",
    updatedAt: "2025-02-15T10:45:00Z",
  },
  {
    id: 9,
    title: "Tavsiye Bonusu Kampanyası",
    slug: "tavsiye-bonusu-kampanyasi",
    description:
      "Arkadaşını getir, ikisini de kazan! Tavsiye ettiğin her arkadaş için hem sen hem de arkadaşın %20 indirim kazanın.",
    shortDescription: "Arkadaş tavsiyesinde her iki tarafa %20 indirim",
    campaignType: "REFERRAL_BONUS",
    discountType: "PERCENTAGE",
    discountAmount: 0,
    discountPercentage: 20,
    maxDiscountAmount: 5000,
    minPurchaseAmount: 3000,
    status: "ACTIVE",
    isFeatured: true,
    isPublic: true,
    targetAudience: "ALL",
    targetAgeMin: 3,
    targetAgeMax: 18,
    promoCode: "REFERRAL20",
    bonusFeatures: "Çift taraflı kazanç sistemi",
    badgeText: "Tavsiye Bonusu",
    badgeColor: "#E91E63",
    thumbnailImageUrl:
      "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400&h=300&fit=crop&crop=center",
    bannerImageUrl:
      "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=1200&h=400&fit=crop&crop=center",
    startDate: "2025-02-01",
    endDate: "2025-09-30",
    academicYear: "2025-2026",
    termsAndConditions:
      "Tavsiye bonusu her iki taraf için de geçerlidir. Tavsiye edilen kişinin kaydolması gerekir.",
    metaTitle: "Tavsiye Bonusu Kampanyası",
    metaDescription:
      "Arkadaşını getir, ikisini de kazan! Her iki tarafa %20 indirim.",
    metaKeywords: "tavsiye, referans, bonus, indirim, kampanya",
    viewCount: 11200,
    clickCount: 2900,
    applicationCount: 178,
    conversionCount: 134,
    conversionRate: 75.3,
    usageLimit: 400,
    usageCount: 134,
    priority: 1,
    isActive: true,
    isExpired: false,
    daysRemaining: 210,
    createdAt: "2025-01-15T14:00:00Z",
    updatedAt: "2025-03-01T16:20:00Z",
  },
  {
    id: 10,
    title: "Burs Kampanyası",
    slug: "burs-kampanyasi",
    description:
      "Başarılı öğrencilere burs fırsatı! Akademik başarı kriterlerini karşılayan öğrencilere %75 indirim ve tam burs imkanı.",
    shortDescription: "Başarılı öğrencilere %75 burs indirimi",
    campaignType: "SCHOLARSHIP",
    discountType: "PERCENTAGE",
    discountAmount: 0,
    discountPercentage: 75,
    maxDiscountAmount: 20000,
    minPurchaseAmount: 5000,
    status: "ACTIVE",
    isFeatured: true,
    isPublic: true,
    requiresApproval: true,
    targetAudience: "SPECIFIC_GRADES",
    targetGradeLevels: "9,10,11,12",
    targetAgeMin: 14,
    targetAgeMax: 18,
    promoCode: "BURS75",
    termsAndConditions:
      "Burs kampanyası akademik başarı belgesi ve gelir durumu belgeleri gerektirir. Başvuru süreci vardır.",
    finePrint: "Başvuru sürecinde gerekli belgeler değerlendirilir.",
    badgeText: "Burs Fırsatı",
    badgeColor: "#673AB7",
    thumbnailImageUrl:
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=400&h=300&fit=crop&crop=center",
    bannerImageUrl:
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=1200&h=400&fit=crop&crop=center",
    startDate: "2025-03-01",
    endDate: "2025-08-31",
    registrationDeadline: "2025-07-31",
    academicYear: "2025-2026",
    metaTitle: "Burs Kampanyası",
    metaDescription:
      "Başarılı öğrencilere burs fırsatı! %75 indirim ve tam burs imkanı.",
    metaKeywords: "burs, başarı, indirim, öğrenci, kampanya",
    viewCount: 16800,
    clickCount: 3200,
    applicationCount: 89,
    conversionCount: 23,
    conversionRate: 25.8,
    usageLimit: 50,
    usageCount: 23,
    priority: 1,
    isActive: true,
    isExpired: false,
    daysRemaining: 160,
    createdAt: "2025-02-01T08:00:00Z",
    updatedAt: "2025-03-05T13:15:00Z",
  },
  {
    id: 11,
    title: "Taksit İmkanı Kampanyası",
    slug: "taksit-imkani-kampanyasi",
    description:
      "Eğitim ücretlerini taksitle öde! 12 aya varan taksit seçenekleri ile eğitime başla, aylık ödemelerle devam et.",
    shortDescription: "12 aya varan taksit seçenekleri",
    campaignType: "INSTALLMENT",
    discountType: "NO_DISCOUNT",
    discountAmount: 0,
    discountPercentage: 0,
    status: "ACTIVE",
    isFeatured: false,
    isPublic: true,
    targetAudience: "ALL",
    targetAgeMin: 3,
    targetAgeMax: 18,
    installmentOptions: "3, 6, 9, 12 ay taksit seçenekleri",
    paymentDeadlineDays: 15,
    termsAndConditions:
      "Taksit seçenekleri banka ve kredi kartı türüne göre değişir.",
    badgeText: "Taksit İmkanı",
    badgeColor: "#009688",
    thumbnailImageUrl:
      "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=400&h=300&fit=crop&crop=center",
    bannerImageUrl:
      "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=1200&h=400&fit=crop&crop=center",
    startDate: "2025-01-01",
    endDate: "2025-12-31",
    academicYear: "2025-2026",
    metaTitle: "Taksit İmkanı Kampanyası",
    metaDescription:
      "Eğitim ücretlerini taksitle öde! 12 aya varan taksit seçenekleri.",
    metaKeywords: "taksit, ödeme, kolaylık, kampanya",
    viewCount: 7300,
    clickCount: 1650,
    applicationCount: 298,
    conversionCount: 245,
    conversionRate: 82.2,
    usageLimit: 1000,
    usageCount: 245,
    priority: 4,
    isActive: true,
    isExpired: false,
    daysRemaining: 280,
    createdAt: "2024-12-15T10:00:00Z",
    updatedAt: "2025-02-10T11:30:00Z",
  },
  {
    id: 12,
    title: "Sınırlı Süre Flaş İndirim",
    slug: "sinirli-sure-flas-indirim",
    description:
      "48 saat süren flaş indirim! Bu fırsatı kaçırma, %40 indirimle hemen kayıt ol. Sadece bu hafta sonu geçerli.",
    shortDescription: "48 saatlik flaş %40 indirim",
    campaignType: "FLASH_SALE",
    discountType: "PERCENTAGE",
    discountAmount: 0,
    discountPercentage: 40,
    maxDiscountAmount: 8000,
    minPurchaseAmount: 3500,
    status: "DRAFT",
    isFeatured: true,
    isPublic: false,
    targetAudience: "ALL",
    targetAgeMin: 3,
    targetAgeMax: 18,
    promoCode: "FLASH40",
    ctaText: "Hemen Kayıt Ol",
    ctaUrl: "/kayit",
    badgeText: "Flaş İndirim",
    badgeColor: "#F44336",
    thumbnailImageUrl:
      "https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=400&h=300&fit=crop&crop=center",
    bannerImageUrl:
      "https://images.unsplash.com/photo-1556740738-b6a63e27c4df?w=1200&h=400&fit=crop&crop=center",
    startDate: "2025-03-15",
    endDate: "2025-03-17",
    academicYear: "2025-2026",
    termsAndConditions:
      "Flaş indirim kampanyası 48 saat ile sınırlıdır. Stok durumuna göre sona erebilir.",
    metaTitle: "Sınırlı Süre Flaş İndirim",
    metaDescription:
      "48 saat süren flaş indirim! %40 indirimle hemen kayıt ol.",
    metaKeywords: "flaş, indirim, sınırlı, süre, kampanya",
    viewCount: 0,
    clickCount: 0,
    applicationCount: 0,
    conversionCount: 0,
    conversionRate: 0,
    usageLimit: 100,
    usageCount: 0,
    priority: 1,
    isActive: false,
    isExpired: false,
    daysRemaining: 5,
    createdAt: "2025-03-10T15:00:00Z",
    updatedAt: "2025-03-10T15:00:00Z",
  },
];
