import { InstitutionTypeListDto } from "@/types";

// Search Filter Parameters Mock Data
export const mockSearchFilterParams: InstitutionTypeListDto[] = [
  {
    institutionTypeDto: {
      id: 1,
      name: "private_school",
      displayName: "Özel Okul",
      description: "Özel öğretim kurumları",
      iconUrl: "ph-graduation-cap",
      colorCode: "#3B82F6",
      sortOrder: 1,
      defaultProperties: "age,fee,language",
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
    },
    propertyGroupTypeDtos: [
      {
        id: 1,
        name: "basic_info",
        displayName: "Temel Bilgiler",
        institutionTypeId: 1,
        isActive: true,
        isMultiple: false,
        createdAt: "2024-01-01T00:00:00Z",
        propertyTypes: [
          {
            id: 1,
            name: "age_range",
            displayName: "Yaş Aralığı",
            propertyGroupTypeId: 1,
            isActive: true,
            createdAt: "2024-01-01T00:00:00Z",
            isSelected: false,
          },
          {
            id: 2,
            name: "education_language",
            displayName: "Eğitim Dili",
            propertyGroupTypeId: 1,
            isActive: true,
            createdAt: "2024-01-01T00:00:00Z",
            isSelected: true,
          },
          {
            id: 3,
            name: "monthly_fee",
            displayName: "Aylık Ücret",
            propertyGroupTypeId: 1,
            isActive: true,
            createdAt: "2024-01-01T00:00:00Z",
            isSelected: false,
          },
        ],
      },
      {
        id: 2,
        name: "facilities",
        displayName: "Olanaklar",
        institutionTypeId: 1,
        isActive: true,
        isMultiple: true,
        createdAt: "2024-01-01T00:00:00Z",
        propertyTypes: [
          {
            id: 4,
            name: "sports_center",
            displayName: "Spor Merkezi",
            propertyGroupTypeId: 2,
            isActive: true,
            isSelected: true,
            createdAt: "2024-01-01T00:00:00Z",
          },
          {
            id: 5,
            name: "library",
            displayName: "Kütüphane",
            propertyGroupTypeId: 2,
            isActive: true,
            isSelected: false,
            createdAt: "2024-01-01T00:00:00Z",
          },
          {
            id: 6,
            name: "cafeteria",
            displayName: "Kantin",
            propertyGroupTypeId: 2,
            isActive: true,
            isSelected: true,
            createdAt: "2024-01-01T00:00:00Z",
          },
        ],
      },
    ],
  },
  {
    institutionTypeDto: {
      id: 2,
      name: "university",
      displayName: "Üniversite",
      description: "Yükseköğretim kurumları",
      iconUrl: "ph-building",
      colorCode: "#10B981",
      sortOrder: 2,
      defaultProperties: "faculty,program,fee",
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
    },
    propertyGroupTypeDtos: [
      {
        id: 3,
        name: "academic_info",
        displayName: "Akademik Bilgiler",
        institutionTypeId: 2,
        isActive: true,
        isMultiple: false,
        createdAt: "2024-01-01T00:00:00Z",
        propertyTypes: [
          {
            id: 7,
            name: "faculty_count",
            displayName: "Fakülte Sayısı",
            propertyGroupTypeId: 3,
            isActive: true,
            isSelected: false,
            createdAt: "2024-01-01T00:00:00Z",
          },
          {
            id: 8,
            name: "program_type",
            displayName: "Program Türü",
            propertyGroupTypeId: 3,
            isActive: true,
            isSelected: true,
            createdAt: "2024-01-01T00:00:00Z",
          },
          {
            id: 9,
            name: "annual_fee",
            displayName: "Yıllık Ücret",
            propertyGroupTypeId: 3,
            isActive: true,
            isSelected: false,
            createdAt: "2024-01-01T00:00:00Z",
          },
        ],
      },
      {
        id: 4,
        name: "campus_facilities",
        displayName: "Kampüs Olanakları",
        institutionTypeId: 2,
        isActive: true,
        isMultiple: true,
        createdAt: "2024-01-01T00:00:00Z",
        propertyTypes: [
          {
            id: 10,
            name: "dormitory",
            displayName: "Yurt",
            propertyGroupTypeId: 4,
            isActive: true,
            isSelected: true,
            createdAt: "2024-01-01T00:00:00Z",
          },
          {
            id: 11,
            name: "research_lab",
            displayName: "Araştırma Laboratuvarı",
            propertyGroupTypeId: 4,
            isActive: true,
            isSelected: false,
            createdAt: "2024-01-01T00:00:00Z",
          },
          {
            id: 12,
            name: "conference_hall",
            displayName: "Konferans Salonu",
            propertyGroupTypeId: 4,
            isActive: true,
            isSelected: true,
            createdAt: "2024-01-01T00:00:00Z",
          },
        ],
      },
    ],
  },
  {
    institutionTypeDto: {
      id: 3,
      name: "course_center",
      displayName: "Kurs Merkezi",
      description: "Özel kurs ve eğitim merkezleri",
      iconUrl: "ph-student",
      colorCode: "#F59E0B",
      sortOrder: 3,
      defaultProperties: "course_type,duration,fee",
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
    },
    propertyGroupTypeDtos: [
      {
        id: 5,
        name: "course_details",
        displayName: "Kurs Detayları",
        institutionTypeId: 3,
        isActive: true,
        isMultiple: false,
        createdAt: "2024-01-01T00:00:00Z",
        propertyTypes: [
          {
            id: 13,
            name: "course_category",
            displayName: "Kurs Kategorisi",
            propertyGroupTypeId: 5,
            isActive: true,
            isSelected: true,
            createdAt: "2024-01-01T00:00:00Z",
          },
          {
            id: 14,
            name: "course_duration",
            displayName: "Kurs Süresi",
            propertyGroupTypeId: 5,
            isActive: true,
            isSelected: false,
            createdAt: "2024-01-01T00:00:00Z",
          },
          {
            id: 15,
            name: "class_size",
            displayName: "Sınıf Mevcudu",
            propertyGroupTypeId: 5,
            isActive: true,
            isSelected: true,
            createdAt: "2024-01-01T00:00:00Z",
          },
        ],
      },
      {
        id: 6,
        name: "schedule_info",
        displayName: "Program Bilgileri",
        institutionTypeId: 3,
        isActive: true,
        isMultiple: true,
        createdAt: "2024-01-01T00:00:00Z",
        propertyTypes: [
          {
            id: 16,
            name: "schedule_flexibility",
            displayName: "Program Esnekliği",
            propertyGroupTypeId: 6,
            isActive: true,
            isSelected: false,
            createdAt: "2024-01-01T00:00:00Z",
          },
          {
            id: 17,
            name: "online_support",
            displayName: "Online Destek",
            propertyGroupTypeId: 6,
            isActive: true,
            isSelected: true,
            createdAt: "2024-01-01T00:00:00Z",
          },
          {
            id: 18,
            name: "certificate_type",
            displayName: "Sertifika Türü",
            propertyGroupTypeId: 6,
            isActive: true,
            isSelected: false,
            createdAt: "2024-01-01T00:00:00Z",
          },
        ],
      },
    ],
  },
];
